unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set -g status-keys vi
setw -g mode-keys vi

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind / split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

set -s copy-command 'clip-copy'

bind U copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel

bind C-v run-shell 'clip-paste | tmux load-buffer -b clip - \; paste-buffer -b clip -d -t #{pane_id}'

if-shell 'infocmp tmux-256color >/dev/null 2>&1' \
	'set -g default-terminal "tmux-256color"' \
	'set -g default-terminal "screen-256color"'

set -sa terminal-features ',xterm-256color:RGB'
set -s escape-time 10

set-option -g set-titles on
set-option -g set-titles-string "#S / #W / #T"
